services:
  stremio-web:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped

  stremio-streaming-server:
    image: stremio/server:latest
    ports:
      - "11470:11470"
    volumes:
      - streaming-server-data:/root/.stremio-server
    restart: unless-stopped

volumes:
  streaming-server-data:
