services:
  stremio-web:
    build: .
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - stremio-network

  stremio-streaming-server:
    image: stremio/server:latest
    expose:
      - "11470"
    volumes:
      - streaming-server-data:/root/.stremio-server
    restart: unless-stopped
    networks:
      - stremio-network

networks:
  stremio-network:
    driver: bridge

volumes:
  streaming-server-data:
